baseURL = "https://mitesh1612.github.io/hugo-blog"
title = "Mitesh Shah's Blog"
paginate = 5
theme = "hugo-PaperMod"
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
title = "Mitesh Shah's Blog"
description = "Developer Blog of Mitesh Shah"
author = "Mitesh Shah"
images = "<link or path of image for opengraph, twitter-cards>"
ShowReadingTime = true
ShowShareButtons = true
comments = false
defaultTheme = "auto"
disableThemeToggle = false
disableSpecial1stPost = false

  [params.assets]
  favicon = "favicon/favicon.ico"
  favicon16x16 = "favicon/favicon-16x16.png"
  favicon32x32 = "favicon/favicon-32x32.png"
  apple_touch_icon = "favicon/apple-touch-icon.png"

  [params.label]
  text = "Home"
  icon = "favicon/apple-touch-icon.png"
  iconHeight = 35

  [params.profileMode]
  enabled = false
  title = "Mitesh Shah's Blog"

    [[params.profileMode.buttons]]
    name = "Posts"
    url = "posts"

    [[params.profileMode.buttons]]
    name = "Tags"
    url = "tags"

  [params.homeInfoParams]
  Title = "Hi there 👋"
  Content = "Welcome to my blog"

  [[params.socialIcons]]
  name = "twitter"
  url = "https://twitter.com/mitesh_1612"

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/mitesh1612"

[params.analytics.google]
SiteVerificationTag = "XYZabc"
