baseURL = "https://mitesh1612.github.io/hugo-blog"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Mitesh Shah's Blog"
theme = "papercss-hugo-theme"
googleAnalytics = "UA-123456789-1"

[taxonomies]
  tag = "tags"

[permalinks]
  post = "/:filename/"

[imaging]
  quality = 99

[params]
  homeMetaContent = "The developer blog of Mitesh Shah"
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat = "Jan 2, 2006"

[menu]
  [[menu.nav]]
    name = "Blog"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "Tags"
    url = "/tags/"
    weight = 2
  [[menu.nav]]
    name = "About"
    url = "/about/"
    weight = 3
  [[menu.nav]]
    name = "RSS"
    url = "/index.xml"
    weight = 4